// export const listadoProductos = [
//     { 
//         id:'1',
//         category: "Apple",
//         description: "Probamos nuestras carcasas Limitless 4.0 en condiciones extremas, mucho más allá de lo que pueda pasar por su carcasa. Esto le da total confianza para poder confiar en Limitless 4.0 para el uso diario, ¡sin importar cómo se vea su día a día!",
//         img:"https://http2.mlstatic.com/D_NQ_NP_978658-MLU48243310395_112021-O.webp" ,
//         name: "Mous Case Limitless 4.0 iPhone 13 Magsafe - Cover Company",
//         price: 2200,
//         stock: 10
//     },

//     { 
//         id:'2',
//         category: "Apple",
//         description: "Limitless 4.0 es altamente innovador: para minimizar el material entre la matriz magnética y los complementos magnéticos, nuestros imanes se han integrado en una ranura poco profunda entre las capas de la carcasa, lo que garantiza una conexión potente con sus accesorios.",
//         img:"https://http2.mlstatic.com/D_NQ_NP_971093-MLU49379806553_032022-O.webp" ,
//         name: "Mous Case Limitless 4.0 iPhone 13 Pro Max Magsafe - Cover",
//         price: 2200,
//         stock: 15,
//     },
//     { 
//         id:'3',
//         category: "Apple",
//         description: "Nuestras fundas Limitless 3.0 están diseñadas para ser lo más útiles posible: hemos incorporado un soporte de tarjeta SIM adicional en el diseño, junto con un ojal a través del cual puede colocar una correa para la muñeca, lo que le brinda la funda más versátil imaginable.",
//         img:"https://http2.mlstatic.com/D_NQ_NP_662405-MLU44883761594_022021-O.webp" ,
//         name: "Mous Case Limitless 3.0 iPhone 12 Y iPhone 12 Pro - Cover Co",
//         price: 1800,
//         stock: 3,
//     },
//     { 
//         id:'4',
//         category: "Apple",
//         description: "Diseño fino y transparente: muestra tu teléfono en esta funda delgada, resistente a los rayos UV y a la decoloración para garantizar que tu funda permanezca transparente durante más tiempo.",
//         img:"https://http2.mlstatic.com/D_NQ_NP_767363-MLU44883913776_022021-O.webp" ,
//         name: "Mous Case Clarity iPhone 12 Y iPhone 12 Pro - Cover Co",
//         price: 1999,
//         stock: 6,
//     },
//     { 
//         id:'5',
//         category: "Apple",
//         description: "Limitless 4.0 es altamente innovador: para minimizar el material entre la matriz magnética y los complementos magnéticos, nuestros imanes se han integrado en una ranura poco profunda entre las capas de la carcasa, lo que garantiza una conexión potente con sus accesorios.",
//         img:"https://http2.mlstatic.com/D_NQ_NP_931957-MLU44446308106_122020-O.webp" ,
//         name: "Funda Carcasa iPhone 12 Pro Max Mous Limitless 3.0 Cover Co",
//         price: 2350,
//         stock: 17,
//     },
//     { 
//         id:'6',
//         category: "Apple",
//         description: "bla bla.",
//         img:"https://http2.mlstatic.com/D_NQ_NP_931957-MLU44446308106_122020-O.webp" ,
//         name: "Funda Carcasa iPhone 12",
//         price: 2350,
//         stock: 17,
//     },
//     { 
//         id:'7',
//         category: "Samsung",
//         description: "bla bla.",
//         img:"https://http2.mlstatic.com/D_NQ_NP_931957-MLU44446308106_122020-O.webp" ,
//         name: "Samsung",
//         price: 2350,
//         stock: 17,
//     },
// ]